<Project>
    <PropertyGroup>
        <BaseOutputPath>$(MSBuildThisFileDirectory)Build\</BaseOutputPath>
        <AppendTargetFrameworkToOutputPath>true</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    </PropertyGroup>
</Project>