<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>14</LangVersion>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
        <!-- Debug 配置追加符号 -->
        <DefineConstants>$(DefineConstants);MyDebug</DefineConstants>
    </PropertyGroup>
    <!-- 将编译后的着色器文件设置为嵌入式资源 -->
    <ItemGroup>
        <EmbeddedResource Include="Assets\Shader\Compiled\**">
            <LogicalName>%(Filename)%(Extension)</LogicalName>
        </EmbeddedResource>
        
    </ItemGroup>

    <!-- 其他资源文件仍然复制到输出目录 -->
    <!-- 其他资源文件复制到输出目录，但排除编译后的着色器文件 -->
    <ItemGroup>
        <None Update="Assets\**">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
        </None>
        
        <!-- 移除编译后的着色器文件，避免重复包含 -->
        <None Remove="Assets\Shader\Compiled\*" />
        <None Remove="Assets\Level\imgui.ini" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Assets\Audio\" />
      <Folder Include="Assets\Level\" />
      <Folder Include="obj\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Engine\Engine.csproj" />
    </ItemGroup>

</Project>
