using Friflo.Engine.ECS; 
namespace Content.Source.Test_Sample.Components;
/*public struct Component1:IComponent{}
public struct Component2:IComponent{}
public struct Component3:IComponent{}
public struct Component4:IComponent{}
public struct Component5:IComponent{}
public struct Component6:IComponent{}
public struct Component7:IComponent{}
public struct Component8:IComponent{}
public struct Component9:IComponent{}
public struct Component10:IComponent{}
public struct Component11:IComponent{}
public struct Component12:IComponent{}
public struct Component13:IComponent{}
public struct Component14:IComponent{}
public struct Component15:IComponent{}
public struct Component16:IComponent{}
public struct Component17:IComponent{}
public struct Component18:IComponent{}
public struct Component19:IComponent{}
public struct Component20:IComponent{}
public struct Component21:IComponent{}
public struct Component22:IComponent{}
public struct Component23:IComponent{}
public struct Component24:IComponent{}
public struct Component25:IComponent{}
public struct Component26:IComponent{}
public struct Component27:IComponent{}
public struct Component28:IComponent{}
public struct Component29:IComponent{}
public struct Component30:IComponent{}
public struct Component31:IComponent{}
public struct Component32:IComponent{}
public struct Component33:IComponent{}
public struct Component34:IComponent{}
public struct Component35:IComponent{}
public struct Component36:IComponent{}
public struct Component37:IComponent{}
public struct Component38:IComponent{}
public struct Component39:IComponent{}
public struct Component40:IComponent{}
public struct Component41:IComponent{}
public struct Component42:IComponent{}
public struct Component43:IComponent{}
public struct Component44:IComponent{}
public struct Component45:IComponent{}
public struct Component46:IComponent{}
public struct Component47:IComponent{}
public struct Component48:IComponent{}
public struct Component49:IComponent{}
public struct Component50:IComponent{}
public struct Component51:IComponent{}
public struct Component52:IComponent{}
public struct Component53:IComponent{}
public struct Component54:IComponent{}
public struct Component55:IComponent{}
public struct Component56:IComponent{}
public struct Component57:IComponent{}
public struct Component58:IComponent{}
public struct Component59:IComponent{}
public struct Component60:IComponent{}
public struct Component61:IComponent{}
public struct Component62:IComponent{}
public struct Component63:IComponent{}
public struct Component64:IComponent{}
public struct Component65:IComponent{}
public struct Component66:IComponent{}
public struct Component67:IComponent{}
public struct Component68:IComponent{}
public struct Component69:IComponent{}
public struct Component70:IComponent{}
public struct Component71:IComponent{}
public struct Component72:IComponent{}
public struct Component73:IComponent{}
public struct Component74:IComponent{}
public struct Component75:IComponent{}
public struct Component76:IComponent{}
public struct Component77:IComponent{}
public struct Component78:IComponent{}
public struct Component79:IComponent{}
public struct Component80:IComponent{}
public struct Component81:IComponent{}
public struct Component82:IComponent{}
public struct Component83:IComponent{}
public struct Component84:IComponent{}
public struct Component85:IComponent{}
public struct Component86:IComponent{}
public struct Component87:IComponent{}
public struct Component88:IComponent{}
public struct Component89:IComponent{}
public struct Component90:IComponent{}
public struct Component91:IComponent{}
public struct Component92:IComponent{}
public struct Component93:IComponent{}
public struct Component94:IComponent{}
public struct Component95:IComponent{}
public struct Component96:IComponent{}
public struct Component97:IComponent{}
public struct Component98:IComponent{}
public struct Component99:IComponent{}
public struct Component100:IComponent{}
public struct Component101:IComponent{}
public struct Component102:IComponent{}
public struct Component103:IComponent{}
public struct Component104:IComponent{}
public struct Component105:IComponent{}
public struct Component106:IComponent{}
public struct Component107:IComponent{}
public struct Component108:IComponent{}
public struct Component109:IComponent{}
public struct Component110:IComponent{}
public struct Component111:IComponent{}
public struct Component112:IComponent{}
public struct Component113:IComponent{}
public struct Component114:IComponent{}
public struct Component115:IComponent{}
public struct Component116:IComponent{}
public struct Component117:IComponent{}
public struct Component118:IComponent{}
public struct Component119:IComponent{}
public struct Component120:IComponent{}
public struct Component121:IComponent{}
public struct Component122:IComponent{}
public struct Component123:IComponent{}
public struct Component124:IComponent{}
public struct Component125:IComponent{}
public struct Component126:IComponent{}
public struct Component127:IComponent{}
public struct Component128:IComponent{}
public struct Component129:IComponent{}
public struct Component130:IComponent{}
public struct Component131:IComponent{}
public struct Component132:IComponent{}
public struct Component133:IComponent{}
public struct Component134:IComponent{}
public struct Component135:IComponent{}
public struct Component136:IComponent{}
public struct Component137:IComponent{}
public struct Component138:IComponent{}
public struct Component139:IComponent{}
public struct Component140:IComponent{}
public struct Component141:IComponent{}
public struct Component142:IComponent{}
public struct Component143:IComponent{}
public struct Component144:IComponent{}
public struct Component145:IComponent{}
public struct Component146:IComponent{}
public struct Component147:IComponent{}
public struct Component148:IComponent{}
public struct Component149:IComponent{}
public struct Component150:IComponent{}
public struct Component151:IComponent{}
public struct Component152:IComponent{}
public struct Component153:IComponent{}
public struct Component154:IComponent{}

public struct Component155:IComponent{}
public struct Component156:IComponent{}
public struct Component157:IComponent{}
public struct Component158:IComponent{}
public struct Component159:IComponent{}
public struct Component160:IComponent{}
public struct Component161:IComponent{}
public struct Component162:IComponent{}
public struct Component163:IComponent{}
public struct Component164:IComponent{}
public struct Component165:IComponent{}
public struct Component166:IComponent{}
public struct Component167:IComponent{}
public struct Component168:IComponent{}
public struct Component169:IComponent{}
public struct Component170:IComponent{}
public struct Component171:IComponent{}
public struct Component172:IComponent{}
public struct Component173:IComponent{}
public struct Component174:IComponent{}
public struct Component175:IComponent{}
public struct Component176:IComponent{}
public struct Component177:IComponent{}
public struct Component178:IComponent{}
public struct Component179:IComponent{}
public struct Component180:IComponent{}
public struct Component181:IComponent{}
public struct Component182:IComponent{}
public struct Component183:IComponent{}
public struct Component184:IComponent{}
public struct Component185:IComponent{}
public struct Component186:IComponent{}
public struct Component187:IComponent{}
public struct Component188:IComponent{}
public struct Component189:IComponent{}
public struct Component190:IComponent{}
public struct Component191:IComponent{}
public struct Component192:IComponent{}
public struct Component193:IComponent{}
public struct Component194:IComponent{}
public struct Component195:IComponent{}
public struct Component196:IComponent{}
public struct Component197:IComponent{}
public struct Component198:IComponent{}
public struct Component199:IComponent{}
public struct Component200:IComponent{}
public struct Component201:IComponent{}
public struct Component202:IComponent{}
public struct Component203:IComponent{}
public struct Component204:IComponent{}
public struct Component205:IComponent{}
public struct Component206:IComponent{}
public struct Component207:IComponent{}
public struct Component208:IComponent{}
public struct Component209:IComponent{}
public struct Component210:IComponent{}
public struct Component211:IComponent{}
public struct Component212:IComponent{}
public struct Component213:IComponent{}
public struct Component214:IComponent{}
public struct Component215:IComponent{}
public struct Component216:IComponent{}
public struct Component217:IComponent{}
public struct Component218:IComponent{}
public struct Component219:IComponent{}
public struct Component220:IComponent{}
public struct Component221:IComponent{}
public struct Component222:IComponent{}
public struct Component223:IComponent{}
public struct Component224:IComponent{}
public struct Component225:IComponent{}
public struct Component226:IComponent{}
public struct Component227:IComponent{}
public struct Component228:IComponent{}
public struct Component229:IComponent{}
public struct Component230:IComponent{}
public struct Component231:IComponent{}
public struct Component232:IComponent{}
public struct Component233:IComponent{}
public struct Component234:IComponent{}
public struct Component235:IComponent{}
public struct Component236:IComponent{}
public struct Component237:IComponent{}
public struct Component238:IComponent{}
public struct Component239:IComponent{}
public struct Component240:IComponent{}
public struct Component241:IComponent{}
public struct Component242:IComponent{}
public struct Component243:IComponent{}
public struct Component244:IComponent{}
public struct Component245:IComponent{}
public struct Component246:IComponent{}
public struct Component247:IComponent{}
public struct Component248:IComponent{}
public struct Component249:IComponent{}
public struct Component250:IComponent{}
public struct Component251:IComponent{}
public struct Component252:IComponent{}
public struct Component253:IComponent{}
public struct Component254:IComponent{}
public struct Component255:IComponent{}
public struct Component256:IComponent{}*/
public struct Component257:IComponent{}
