<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <HotReloadEnabled>true</HotReloadEnabled>
        <HotReloadPartialTypes>true</HotReloadPartialTypes>
        <RootNamespace>Runner</RootNamespace>
        <LangVersion>14</LangVersion>
        <!--<PublishAot>false</PublishAot>--> <!-- 启用AOT编译 -->
    </PropertyGroup>
    
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
        <AssemblyName>Game</AssemblyName>
        <PublishSingleFile>true</PublishSingleFile>
        <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
        <SelfContained>true</SelfContained>
    </PropertyGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\Content\Content.csproj"/>
        <ProjectReference Include="..\Engine\Engine.csproj" />
    </ItemGroup>
    
    <Target Name="CopySpritesAfterPublish" AfterTargets="Publish">
        <ItemGroup>
            <SpriteFiles Include="..\Content\Assets\Sprites\**\*.*" />
        </ItemGroup>
        <Copy SourceFiles="@(SpriteFiles)"
              DestinationFiles="@(SpriteFiles->'$(PublishDir)Assets\Sprites\%(RecursiveDir)%(Filename)%(Extension)')"
              SkipUnchangedFiles="true" />
    </Target>
</Project>
